apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudify-manager-rabbitmq
  labels:
    app: cloudify-manager
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudify-manager
      component: rabbitmq
  template:
    metadata:
      labels:
        app: cloudify-manager
        component: rabbitmq
    spec:
      containers:
        - name: cloudify-manager-rabbitmq
          ports:
            - containerPort: 5671
              hostPort: 5671
            - containerPort: 15671
              hostPort: 15671
            - containerPort: 53333
              hostPort: 53333
          image: eu.gcr.io/trammell-project/docker-cfy-manager-rabbitmq
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - mountPath: /run
              name: mq-tmpfs-run
            - mountPath: /run/user
              name: mq-tmpfs-run-user
            - mountPath: /run/lock
              name: mq-tmpfs-run-lock
            - mountPath: /sys/fs/cgroup
              readOnly: True
              name: cgroup
      volumes:
        - name: mq-tmpfs-run
          emptyDir: {}
        - name: mq-tmpfs-run-user
          emptyDir: {}
        - name: mq-tmpfs-run-lock
          emptyDir: {}
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
---
# cloudify-manager-rabbitmq.default.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: cloudify-manager-rabbitmq
  labels:
    app: cloudify-manager
    component: rabbitmq
spec:
  selector:
    app: cloudify-manager
    component: rabbitmq
  ports:
    - name: rabbit
      protocol: TCP
      port: 5671
    - name: rabbit-interface
      protocol: TCP
      port: 15671
    - name: mq-fileserver
      protocol: TCP
      port: 53333
