apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudify-manager-worker
  labels:
    app: cloudify-manager
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudify-manager
      component: worker
  template:
    metadata:
      labels:
        app: cloudify-manager
        component: worker
    spec:
      containers:
        - name: cloudify-manager-worker
          ports:
            - containerPort: 80
              hostPort: 20080
            - containerPort: 443
              hostPort: 443
            - containerPort: 8086
              hostPort: 8086
            - containerPort: 8080
              hostPort: 8080
            - containerPort: 8300
              hostPort: 8300
            - containerPort: 8301
              hostPort: 8301
              protocol: TCP
            - containerPort: 8301
              hostPort: 8301
              protocol: UDP
            - containerPort: 8500
              hostPort: 8500
            - containerPort: 9999
              hostPort: 9999
            - containerPort: 22000
              hostPort: 22000
            - containerPort: 53333
              hostPort: 53333
          image: eu.gcr.io/trammell-project/docker-cfy-manager-worker
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - mountPath: /run
              name: cfy-tmpfs-run
            - mountPath: /run/user
              name: cfy-tmpfs-run-user
            - mountPath: /run/lock
              name: cfy-tmpfs-run-lock
            - mountPath: /sys/fs/cgroup
              readOnly: True
              name: cgroup
      volumes:
        - name: cfy-tmpfs-run
          emptyDir: {}
        - name: cfy-tmpfs-run-user
          emptyDir: {}
        - name: cfy-tmpfs-run-lock
          emptyDir: {}
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
---
apiVersion: v1
kind: Service
metadata:
  name: cloudify-manager-worker
  labels:
    app: cloudify-manager
    component: worker
spec:
  selector:
    app: cloudify-manager
    component: worker
  type: LoadBalancer
  ports:
    - name: cfy-ssh
      protocol: TCP
      port: 22
    - name: cfy-http
      protocol: TCP
      port: 80
    - name: cfy-https
      protocol: TCP
      port: 443
    - name: influx
      protocol: TCP
      port: 8086
    - name: cfy-ui
      protocol: TCP
      port: 8088
    - name: cfy-internal-kv
      protocol: TCP
      port: 8300
    - name: cfy-tcp-heartbeat
      protocol: TCP
      port: 8301
    - name: cfy-logstash
      protocol: TCP
      port: 9999
    - name: cfy-fileserver-ha
      protocol: TCP
      port: 22000
    - name: cfy-fileserver
      protocol: TCP
      port: 53333
