#!/usr/bin/env bash

source resource-utils
source create-certificates
source configure-pods


# Create Manager Pods
# kubectl apply -f resources/

log_message "Ignore the last message, we are now....ADDING new pods!"

export NEW_POD=$1
export PASSWORD=$2

export POSTGRES_PODS=$(kubectl get pods --selector app=cloudify-manager --selector component=postgresql | awk '{if(NR>1)print $1}')
export RABBITMQ_PODS=$(kubectl get pods --selector app=cloudify-manager --selector component=rabbitmq | awk '{if(NR>1)print $1}')
export CFYWORKERPODS=$(kubectl get pods --selector app=cloudify-manager --selector component=worker | awk '{if(NR>1)print $1}')
export ACTIVE_WORKER_POD=$(kubectl get pods --sort-by=.metadata.creationTimestamp --selector app=cloudify-manager --selector component=worker | awk '{if(NR>1)print $1}' | head -n 1)
export ACTIVE_MANAGER_IP=$(retry_get_private_ip $ACTIVE_WORKER_POD)

log_message "List of pods: ${POSTGRES_PODS}, ${RABBITMQ_PODS}, ${CFYWORKERPODS}"

# Create the Certificates and Keys
create_csr_and_cert $NEW_POD worker client

# Configure the Pods
configure_pod ${NEW_POD} worker ${ACTIVE_MANAGER_IP} ${PASSWORD}

log_message "OK Done. Listing out the stuff we made:"

kubectl get pv
kubectl get pvc
kubectl get deploy
kubectl get po
kubectl get svc

log_message "FINISHED UPPING ADDING NEW POD!!!!!!!!!"
