#!/usr/bin/env bash

wget https://s3-eu-west-1.amazonaws.com/cloudify-release-eu/cloudify/5.0.0/.dev1-release/cloudify-postgresql-docker-5.0.0.dev1.tar
wget https://s3-eu-west-1.amazonaws.com/cloudify-release-eu/cloudify/5.0.0/.dev1-release/cloudify-rabbitmq-docker-5.0.0.dev1.tar
wget https://s3-eu-west-1.amazonaws.com/cloudify-release-eu/cloudify/5.0.0/.dev1-release/cloudify-manager_worker-docker-5.0.0.dev1.tar

for i in cloudify-manager_worker-docker-5.0.0.dev1.tar cloudify-postgresql-docker-5.0.0.dev1.tar cloudify-rabbitmq-docker-5.0.0.dev1.tar
do
    docker load -i $i;
done
