#!/usr/bin/env bash

wget https://s3-eu-west-1.amazonaws.com/cloudify-release-eu/cloudify/5.0.0/.dev1-release/cloudify-manager_worker-docker-5.0.0.dev1.tar
docker tag cloudify-manager_worker-docker-5.0.0.dev1.tar eu.gcr.io/trammell-project/docker-cfy-manager-worker:latest
docker push cloudify-manager_worker-docker-5.0.0.dev1.tar eu.gcr.io/trammell-project/docker-cfy-manager-worker:latest

wget https://s3-eu-west-1.amazonaws.com/cloudify-release-eu/cloudify/5.0.0/.dev1-release/cloudify-rabbitmq-docker-5.0.0.dev1.tar
docker tag cloudify-rabbitmq-docker-5.0.0.dev1.tar eu.gcr.io/trammell-project/docker-cfy-manager-rabbitmq:latest
docker push cloudify-rabbitmq-docker-5.0.0.dev1.tar eu.gcr.io/trammell-project/docker-cfy-manager-rabbitmq:latest

wget https://s3-eu-west-1.amazonaws.com/cloudify-release-eu/cloudify/5.0.0/.dev1-release/cloudify-postgresql-docker-5.0.0.dev1.tar
docker tag cloudify-postgresql-docker-5.0.0.dev1.tar eu.gcr.io/trammell-project/docker-cfy-manager-postgresql:latest
docker push cloudify-postgresql-docker-5.0.0.dev1.tar eu.gcr.io/trammell-project/docker-cfy-manager-postgresql:latest

