#!/usr/bin/env bash

source resource-utils
source create-certificates
source configure-pods
source create-root-certificate

set_cloudify_manager_defaults

setup_all_pods
check_pods_ready ${ALL_PODS[@]}
certify_pods ${ALL_PODS[@]}
configure_all_pods ${ALL_PODS[@]}

final_log_message
